name: Openwrt Build Bot
on:
  schedule:
  - cron: 0 16 * * *

jobs:
  check:
    name: Check new version of Clash.Meta
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: EkkoG/openwrt-packages-version-checker@main
        env:
          COMMIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: MetaCubeX/Clash.Meta
          BRANCH: main
