name: Openwrt Packages Build Bot for 22.03
on:
  push:
    branches: master
    paths:
      - '.github/workflows/build-packages-release-22.03.yml'
      - 'scripts/patch.sh'
      - 'packages/**'
      - '!packages/**/github/workflows/**'
      - '!packages/**/README*'
      - '!**/.gitignore'
      - '!packages/**/LICENSE'
      - '!packages/**/LICENSES'

jobs:
  buildpkg:
    name: Build Openwrt Package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x86_64-22.03.3

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Prepare feeds
        run: |
          ./scripts/patch.sh ${{ matrix.arch }}
          cp Makefile2 packages/sdm/Makefile
          cat packages/sdm/Makefile

      - name: Build
        uses: ekkog/gh-action-sdk@master
        env:
          ARCH: ${{ matrix.arch }}
          KEY_BUILD: ${{ secrets.KEY_BUILD }}
          INDEX: 1
          IGNORE_ERRORS: 1
          FEED_DIR: $GITHUB_WORKSPACE/packages
          PACKAGES: |
            sdm
            v2dat
            v2ray-geodata


      - name: List files
        run: |
          ls -R bin/

      - name: Upload
        env:
          ARCH: ${{ matrix.arch }}
        run: |
          BRANCH="testpackages/${ARCH::-2}"
          cd bin/packages/*/action
          sudo chown runner:runner -R .
          git init
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add .
          git commit -m "$(TZ='Asia/Shanghai' date +@%Y%m%d)"
          git push --force --quiet "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY" HEAD:$BRANCH

