name: Openwrt Build Bot for 21.02
on:
  push:
    branches: master
    paths:
      - '**'
      - '!README.md'
      - '!.gitignore'
      - '!.github/workflows/build-release-22.03.yml'
      - '!.github/workflows/build-snapshot.yml'
      - '!.github/workflows/check.yml'
      - '!.github/workflows/build-immortalwrt-snapshot.yml'
  schedule:
  - cron: 0 */6 * * *

jobs:
  buildpkg:
    name: Build Openwrt Package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - aarch64_cortex-a53-21.02.5
          - aarch64_cortex-a72-21.02.5
          - aarch64_generic-21.02.5
          - arc_arc700-21.02.5
          - arc_archs-21.02.5
          - arm_arm1176jzf-s_vfp-21.02.5
          - arm_arm926ej-s-21.02.5
          - arm_cortex-a15_neon-vfpv4-21.02.5
          - arm_cortex-a5_vfpv4-21.02.5
          - arm_cortex-a7-21.02.5
          - arm_cortex-a7_neon-vfpv4-21.02.5
          - arm_cortex-a8_vfpv3-21.02.5
          - arm_cortex-a9-21.02.5
          - arm_cortex-a9_neon-21.02.5
          - arm_cortex-a9_vfpv3-d16-21.02.5
          - arm_fa526-21.02.5
          - arm_mpcore-21.02.5
          - arm_xscale-21.02.5
          - i386_pentium-mmx-21.02.5
          - i386_pentium4-21.02.5
          - mips64_octeonplus-21.02.5
          - mips_24kc-21.02.5
          - mips_4kec-21.02.5
          - mips_mips32-21.02.5
          - mipsel_24kc-21.02.5
          - mipsel_24kc_24kf-21.02.5
          - mipsel_74kc-21.02.5
          - mipsel_mips32-21.02.5
          - powerpc_464fp-21.02.5
          - powerpc_8540-21.02.5
          - x86_64-21.02.5

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare feeds
        run: |
          ./feed_build.sh
          current_md5=$(./get_md5.sh)
          if [ -f .21_last_feed_md5 ]; then
              last_md5=$(cat .21_last_feed_md5)

              echo "Current feeds md5: $current_md5"
              echo "Last feeds md5: $last_md5"

              if [ "$current_md5" = "$last_md5" ]; then
                  echo "No changes in feeds, skip build"
                  echo "SKIP_BUILD=1" >> $GITHUB_ENV
              else
                  echo "Feeds changed, continue build"
                  # diff current_md5 last_md5
                  diff_result=$(diff <(echo "$current_md5") <(echo "$last_md5") -y | echo "$(cat -)")
                  echo "$diff_result"
              fi
          fi
          echo "$current_md5" > .21_last_feed_md5
          ./patch.sh
          ./get_md5.sh > .21_last_build_md5

      - name: Build
        uses: openwrt/gh-action-sdk@v5.4
        if: ${{ env.SKIP_BUILD != 1 }}
        env:
          ARCH: ${{ matrix.arch }}
          KEY_BUILD: ${{ secrets.KEY_BUILD }}
          INDEX: 1
          IGNORE_ERRORS: 1
          PACKAGES: |
            natmap
            luci-app-natmap
            clash-meta-for-openclash
            clash-for-openclash
            sdm
            mosdns
            luci-app-mosdns
            luci-theme-argon
            luci-app-openclash
            luci-app-temp-status

      - name: List files
        if: ${{ env.SKIP_BUILD != 1 }}
        run: |
          ls -R bin/

      - name: Upload
        if: ${{ env.SKIP_BUILD != 1 }}
        env:
          ARCH: ${{ matrix.arch }}
        run: |
          BRANCH="packages/${ARCH::-2}"
          if [[ $ARCH =~ "snapshot" ]]; then
              BRANCH="packages/$ARCH"
          fi
          cd bin/packages/*/action
          sudo chown runner:runner -R .
          git init
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add .
          git commit -m "$(TZ='Asia/Shanghai' date +@%Y%m%d)"
          git push --force --quiet "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY" HEAD:$BRANCH

      - name: Commit
        if: ${{ env.SKIP_BUILD != 1 }}
        run: |
          cd $GITHUB_WORKSPACE

          git config --global user.name "bot"
          git config --global user.email "bot@github.com"

          git add .

          git commit -m "Update feeds"
          git push --quiet "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY" HEAD:master
