name: Openwrt Build Bot
on:
  push:
    branches: master
    paths:
      - '**'
      - '!README.md'
      - '!.gitignore'
  schedule:
  - cron: 0 0 * * *

jobs:
  buildpkg:
    name: Build Openwrt Package
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch:
          - x86_64
          - mips_24kc
          - aarch64_generic
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        uses: cielpy/gh-action-sdk@master
        env:
          ARCH: ${{ matrix.arch }}
          KEY_BUILD : ${{ secrets.KEY_BUILD }}
          EXTRA_FEEDS: src-git|garypang13|https://github.com/garypang13/openwrt-packages
          FEEDS_NEED_INSTALL: garypang13
          INDEX: 1
          PACKAGES: |
            tcpping

      - name: List files
        run: |
          ls -R bin

      - name: Upload
        env:
          ARCH: ${{ matrix.arch }}
        run: |
          
          BRANCH="packages/$ARCH"
          # Upload base only
          cd bin/packages/*/garypang13
          git init -b master
          git config user.name "bot"
          git config user.email "bot@github.com"
          git remote set-url origin https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git
          git checkout -b $BRANCH
          git commit -am "Update"
          git push origin master -f

