name: Openwrt Build Bot
on:
  push:
    branches: master
    paths:
      - '**'
      - '!README.md'
      - '!.gitignore'
  schedule:
  - cron: 0 0 * * *

jobs:
  buildpkg:
    name: Build Openwrt Package
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch:
          - x86_64
          - mips_24kc
          - aarch64_generic
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        uses: cielpy/gh-action-sdk@master
        env:
          ARCH: ${{ matrix.arch }}
          KEY_BUILD : ${{ secrets.KEY_BUILD }}
          EXTRA_FEEDS: src-git|garypang13|https://github.com/garypang13/openwrt-packages
          FEEDS_NEED_INSTALL: garypang13
          SCRIPT_BEFORE_BUILD: |
            sed -i 's/libustream-openssl/wget-ssl/' package/feeds/garypang13/luci-app-ssr-plus/Makefile
          INDEX: 1
          PACKAGES: |
            feeds/luci/luci-base
            luci-app-vssr
            luci-app-wrtbwmon
            luci-app-frpc
            luci-app-filetransfer
            luci-app-vlmcsd
            luci-app-zerotier
            luci-app-bypass
            luci-app-dnsfilter
            luci-theme-edge
            chinadns-ng
            smartdns-le
            luci-app-passwall
            luci-app-ssr-plus
            luci-app-adbyby-plus
            luci-app-autoreboot


      - name: List files
        run: |
          ls -R bin

      - name: Upload
        env:
          ARCH: ${{ matrix.arch }}
        run: |
          BRANCH="packages/$ARCH"
          cd bin/packages/*/garypang13
          sudo chown runner:runner -R .
          git init
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add .
          git commit -m "$(TZ='Asia/Shanghai' date +@%Y%m%d)"
          git push --force --quiet "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY" HEAD:$BRANCH

          LUCI_BRANCH="luci/$ARCH"
          cd ../luci
          sudo chown runner:runner -R .
          git init
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add .
          git commit -m "$(TZ='Asia/Shanghai' date +@%Y%m%d)"
          git push --force --quiet "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY" HEAD:$LUCI_BRANCH

          BASE_BRANCH="base/$ARCH"
          cd ../base
          sudo chown runner:runner -R .
          git init
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add .
          git commit -m "$(TZ='Asia/Shanghai' date +@%Y%m%d)"
          git push --force --quiet "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY" HEAD:$BASE_BRANCH

          PKG_BRANCH="origin_packages/$ARCH"
          cd ../packages
          sudo chown runner:runner -R .
          git init
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add .
          git commit -m "$(TZ='Asia/Shanghai' date +@%Y%m%d)"
          git push --force --quiet "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY" HEAD:$PKG_BRANCH