name: Openwrt Build Bot
on:
  push:
    branches: master
    paths:
      - '**'
      - '!README.md'
      - '!.gitignore'
  schedule:
  - cron: 0 17 * * *

jobs:
  buildpkg:
    name: Build Openwrt Package
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch:
          - aarch64_cortex-a53-22.03.3
          - aarch64_cortex-a72-22.03.3
          - aarch64_generic-22.03.3
          - arm_arm1176jzf-s_vfp-22.03.3
          - arm_arm926ej-s-22.03.3
          - arm_cortex-a15_neon-vfpv4-22.03.3
          - arm_cortex-a5_vfpv4-22.03.3
          - arm_cortex-a7-22.03.3
          - arm_cortex-a7_neon-vfpv4-22.03.3
          - arm_cortex-a7_vfpv4-22.03.3
          - arm_cortex-a8_vfpv3-22.03.3
          - arm_cortex-a9-22.03.3
          - arm_cortex-a9_neon-22.03.3
          - arm_cortex-a9_vfpv3-d16-22.03.3
          - arm_fa526-22.03.3
          - arm_mpcore-22.03.3
          - arm_xscale-22.03.3
          - i386_pentium-mmx-22.03.3
          - i386_pentium4-22.03.3
          - mips64_octeonplus-22.03.3
          - mips_24kc-22.03.3
          - mips_4kec-22.03.3
          - mips_mips32-22.03.3
          - mipsel_24kc-22.03.3
          - mipsel_24kc_24kf-22.03.3
          - mipsel_74kc-22.03.3
          - mipsel_mips32-22.03.3
          - powerpc_464fp-22.03.3
          - powerpc_8540-22.03.3
          - x86_64-22.03.3
          - aarch64_cortex-a53-21.02.5
          - aarch64_cortex-a72-21.02.5
          - aarch64_generic-21.02.5
          - arm_arm1176jzf-s_vfp-21.02.5
          - arm_arm926ej-s-21.02.5
          - arm_cortex-a15_neon-vfpv4-21.02.5
          - arm_cortex-a5_vfpv4-21.02.5
          - arm_cortex-a7-21.02.5
          - arm_cortex-a7_neon-vfpv4-21.02.5
          - arm_cortex-a8_vfpv3-21.02.5
          - arm_cortex-a9-21.02.5
          - arm_cortex-a9_neon-21.02.5
          - arm_cortex-a9_vfpv3-d16-21.02.5
          - arm_fa526-21.02.5
          - arm_mpcore-21.02.5
          - arm_xscale-21.02.5
          - i386_pentium-mmx-21.02.5
          - i386_pentium4-21.02.5
          - mips64_octeonplus-21.02.5
          - mips_24kc-21.02.5
          - mips_4kec-21.02.5
          - mips_mips32-21.02.5
          - mipsel_24kc-21.02.5
          - mipsel_24kc_24kf-21.02.5
          - mipsel_74kc-21.02.5
          - mipsel_mips32-21.02.5
          - powerpc_464fp-21.02.5
          - powerpc_8540-21.02.5
          - x86_64-21.02.5

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Prepare feeds
        run: |
          mkdir openwrt-packages

          git clone --depth=1 --branch v5-dev https://github.com/sbwml/luci-app-mosdns.git sbwml-packages
          cp -r sbwml-packages/luci-app-mosdns openwrt-packages/luci-app-mosdns
          rm -r sbwml-packages

          git clone --depth=1 https://github.com/immortalwrt/packages.git immortal-packages
          cp -r immortal-packages/net/mosdns openwrt-packages/mosdns
          cp -r immortal-packages/net/v2ray-geodata openwrt-packages/v2ray-geodata
          sed -i '/golang-package.mk/ c\include $(TOPDIR)/feeds/packages/lang/golang/golang-package.mk' openwrt-packages/mosdns/Makefile
          rm -r immortal-packages

          git clone --depth=1 https://github.com/immortalwrt/luci.git immortal-luci
          cp -r immortal-luci/applications/luci-app-openclash openwrt-packages/luci-app-openclash
          rm -r immortal-luci

          git clone --depth=1 https://github.com/jerrykuku/luci-theme-argon.git openwrt-packages/luci-theme-argon
          git clone --depth=1 https://github.com/gSpotx2f/luci-app-temp-status.git openwrt-packages/luci-app-temp-status
          git clone --depth=1 https://github.com/EkkoG/sdm.git openwrt-packages/sdm
          ls openwrt-packages

          
          wget https://testingcf.jsdelivr.net/gh/alecthw/mmdb_china_ip_list@release/lite/Country.mmdb -O openwrt-packages/luci-app-openclash/root/etc/openclash/Country.mmdb
          wget https://testingcf.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat -O openwrt-packages/luci-app-openclash/root/etc/openclash/GeoSite.dat
          wget https://testingcf.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat -O openwrt-packages/luci-app-openclash/root/etc/openclash/GeoIP.dat


      - name: Build
        uses: ekkog/gh-action-sdk@master
        # only build for 22.03
        # if: ${{ contains(matrix.arch, '22.03') }}
        env:
          ARCH: ${{ matrix.arch }}
          KEY_BUILD: ${{ secrets.KEY_BUILD }}
          INDEX: 1
          EXTRA_SCRIPT_AFTER_UPDATE: |
            git clone https://github.com/openwrt/packages official-packages
            cp -r official-packages/lang/golang feeds/packages/lang/golang
            rm -rf official-packages
          PACKAGES: |
            sdm
            mosdns
            luci-app-mosdns
            luci-theme-argon
            luci-app-openclash
            luci-app-temp-status

      - name: List files
        run: |
          ls -R bin/

      - name: Upload
        env:
          ARCH: ${{ matrix.arch }}
        run: |
          BRANCH="packages/${ARCH::-2}"
          cd bin/packages/*/action
          sudo chown runner:runner -R .
          git init
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add .
          git commit -m "$(TZ='Asia/Shanghai' date +@%Y%m%d)"
          git push --force --quiet "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY" HEAD:$BRANCH