name: Openwrt Build Bot
on:
  push:
    branches: master
    paths:
      - '**'
      - '!README.md'
      - '!.gitignore'
  schedule:
  - cron: 0 17 * * *

jobs:
  buildpkg:
    name: Build Openwrt Package
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch:
          - x86_64-21.02.5
          - x86_64-22.03.2
          - aarch64_generic-21.02.5
          - aarch64_generic-22.03.2
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Prepare feeds
        run: |
          mkdir openwrt-packages

          git clone --depth=1 https://github.com/vernesong/OpenClash.git openwrt-packages/luci-app-openclash
          git clone --depth=1 https://github.com/jerrykuku/luci-theme-argon.git openwrt-packages/luci-theme-argon
          git clone --depth=1 https://github.com/muink/openwrt-Natter.git openwrt-packages/natter

      - name: Build
        uses: ekkog/gh-action-sdk@index
        env:
          ARCH: ${{ matrix.arch }}
          KEY_BUILD: ${{ secrets.KEY_BUILD }}
          EXTRA_FEEDS: src-link|ekkog|/github/workspace/openwrt-packages
          INDEX: 1
          PACKAGES: |
            luci-theme-argon
            luci-app-openclash
            natter


      - name: List files
        run: |
          ls -R bin/

      - name: Upload
        env:
          ARCH: ${{ matrix.arch }}
        run: |
          BRANCH="packages/${ARCH::-2}"
          cd bin/packages/*/action
          sudo chown runner:runner -R .
          git init
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add .
          git commit -m "$(TZ='Asia/Shanghai' date +@%Y%m%d)"
          git push --force --quiet "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY" HEAD:$BRANCH

          LUCI_BRANCH="luci/${ARCH::-2}"
          cd ../luci
          sudo chown runner:runner -R .
          git init
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add .
          git commit -m "$(TZ='Asia/Shanghai' date +@%Y%m%d)"
          git push --force --quiet "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY" HEAD:$LUCI_BRANCH

          BASE_BRANCH="base/${ARCH::-2}"
          cd ../base
          sudo chown runner:runner -R .
          git init
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add .
          git commit -m "$(TZ='Asia/Shanghai' date +@%Y%m%d)"
          git push --force --quiet "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY" HEAD:$BASE_BRANCH

          PKG_BRANCH="origin_packages/${ARCH::-2}"
          cd ../packages
          sudo chown runner:runner -R .
          git init
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add .
          git commit -m "$(TZ='Asia/Shanghai' date +@%Y%m%d)"
          git push --force --quiet "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY" HEAD:$PKG_BRANCH
