name: Openwrt Build Bot
on:
  push:
    branches: master
    paths:
      - '**'
      - '!README.md'
      - '!.gitignore'
  schedule:
  - cron: 0 17 * * *

jobs:
  buildpkg:
    name: Build Openwrt Package
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch:
          - x86_64-21.02.5
          - aarch64_generic-21.02.5
          - mips_24kc
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Prepare feeds
        run: |
          git clone --depth=1 https://github.com/garypang13/openwrt-packages.git
          cd openwrt-packages

          git clone --depth=1 https://github.com/ekkog/overture-openwrt.git overture

      - name: Build
        uses: ekkog/gh-action-sdk@master
        env:
          ARCH: ${{ matrix.arch }}
          KEY_BUILD : ${{ secrets.KEY_BUILD }}
          EXTRA_FEEDS: src-link|ekkog|/github/workspace/openwrt-packages
          FEEDS_NEED_INSTALL: |
            ekkog
          INDEX: 1
          PACKAGES: |
            overture
            libcap
            luci-base
            luci-theme-argon
            luci-theme-edge
            luci-app-vssr
            luci-app-wrtbwmon
            luci-app-frpc
            luci-app-filetransfer
            luci-app-vlmcsd
            luci-app-zerotier
            luci-app-bypass
            luci-app-dnsfilter
            luci-theme-edge
            chinadns-ng
            smartdns
            luci-app-passwall
            luci-app-adbyby-plus
            luci-app-autoreboot


      - name: List files
        run: |
          ls -R bin

      - name: Upload
        env:
          ARCH: ${{ matrix.arch }}
        run: |
          BRANCH="packages/$ARCH"
          cd bin/packages/*/ekkog
          sudo chown runner:runner -R .
          git init
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add .
          git commit -m "$(TZ='Asia/Shanghai' date +@%Y%m%d)"
          git push --force --quiet "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY" HEAD:$BRANCH

          LUCI_BRANCH="luci/$ARCH"
          cd ../luci
          sudo chown runner:runner -R .
          git init
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add .
          git commit -m "$(TZ='Asia/Shanghai' date +@%Y%m%d)"
          git push --force --quiet "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY" HEAD:$LUCI_BRANCH

          BASE_BRANCH="base/$ARCH"
          cd ../base
          sudo chown runner:runner -R .
          git init
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add .
          git commit -m "$(TZ='Asia/Shanghai' date +@%Y%m%d)"
          git push --force --quiet "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY" HEAD:$BASE_BRANCH

          PKG_BRANCH="origin_packages/$ARCH"
          cd ../packages
          sudo chown runner:runner -R .
          git init
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add .
          git commit -m "$(TZ='Asia/Shanghai' date +@%Y%m%d)"
          git push --force --quiet "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY" HEAD:$PKG_BRANCH
