name: Openwrt Build Bot
on:
  push:
    branches: master
    paths:
      - '**'
      - '!README.md'
      - '!.gitignore'
  schedule:
  - cron: 0 17 * * *

jobs:
  buildpkg:
    name: Build Openwrt Package
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64_generic
          - mips_24kc
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Prepare feeds
        run: |
          git clone --depth=1 https://github.com/garypang13/openwrt-packages.git
          cd openwrt-packages
          sed -i 's/libustream-openssl/wget-ssl/' luci-app-ssr-plus/Makefile
          # 编译 node 耗时太长，容易超过 GitHub 资源限制，改成不显示依赖，需要自己安装 node
          sed -i 's/+node //g' luci-app-jd-dailybonus/Makefile
          git clone --depth=1 https://github.com/cielpy/openwrt-clash.git clash
          git clone --depth=1 -b master https://github.com/cielpy/luci-app-clash.git
          git clone --depth=1 https://github.com/cielpy/overture-openwrt.git overture

      - name: Build
        uses: cielpy/gh-action-sdk@master
        env:
          ARCH: ${{ matrix.arch }}
          KEY_BUILD : ${{ secrets.KEY_BUILD }}
          EXTRA_FEEDS: src-link|cielpy|/github/workspace/openwrt-packages
          FEEDS_NEED_INSTALL: |
            cielpy
            packages
          INDEX: 1
          PACKAGES: |
            ubus
            luci-app-jd-dailybonus|mips_24kc
            overture
            clash
            libcap
            luci-base
            luci-theme-argon
            luci-theme-edge
            luci-app-clash
            luci-app-vssr
            luci-app-wrtbwmon
            luci-app-frpc
            luci-app-filetransfer
            luci-app-vlmcsd
            luci-app-zerotier
            luci-app-bypass
            luci-app-dnsfilter
            luci-theme-edge
            chinadns-ng
            smartdns-le
            luci-app-passwall
            luci-app-ssr-plus
            luci-app-adbyby-plus
            luci-app-autoreboot


      - name: List files
        run: |
          ls -R bin

      - name: Upload
        env:
          ARCH: ${{ matrix.arch }}
        run: |
          BRANCH="packages/$ARCH"
          cd bin/packages/*/cielpy
          sudo chown runner:runner -R .
          git init
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add .
          git commit -m "$(TZ='Asia/Shanghai' date +@%Y%m%d)"
          git push --force --quiet "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY" HEAD:$BRANCH

          LUCI_BRANCH="luci/$ARCH"
          cd ../luci
          sudo chown runner:runner -R .
          git init
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add .
          git commit -m "$(TZ='Asia/Shanghai' date +@%Y%m%d)"
          git push --force --quiet "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY" HEAD:$LUCI_BRANCH

          BASE_BRANCH="base/$ARCH"
          cd ../base
          sudo chown runner:runner -R .
          git init
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add .
          git commit -m "$(TZ='Asia/Shanghai' date +@%Y%m%d)"
          git push --force --quiet "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY" HEAD:$BASE_BRANCH

          PKG_BRANCH="origin_packages/$ARCH"
          cd ../packages
          sudo chown runner:runner -R .
          git init
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add .
          git commit -m "$(TZ='Asia/Shanghai' date +@%Y%m%d)"
          git push --force --quiet "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY" HEAD:$PKG_BRANCH
