name: Upstream Packages Version Check
on:
  push:
    branches: master
    paths:
      - '**'
      - '!README.md'
      - '!.gitignore'
      - '!packages/**'
  schedule:
  - cron: 12 */6 * * *

jobs:
  buildpkg:
    name: Fetch feeds
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.COMMIT_TOKEN }}

      - name: Fetch feeds
        run: |
          ./scripts/feed_build.sh

      - name: Commit
        run: |
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add .
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "$(TZ='Asia/Shanghai' date +@%Y%m%d)"
          git push --quiet "https://x-access-token:${{ secrets.COMMIT_TOKEN }}@github.com/$GITHUB_REPOSITORY" HEAD:master